Program GERIND;
{FUP QUE A PARTIR DO ARQUIVO cand.txt GERE UM ARQUIVO PARA ACESSO INDEXADO cand.IND
 IRÁ USAR O CONCEITO DE TAMANHO DE REGISTRO QUE POSSUIRÁ OS CAMPOS:
 NUMERO=INTEGER, NOME=STRING[35], CPF=STRING[11], DATA=STRING[8], INVERTIDA AAAAMMDD, CARGO=INTEGER....
 veja bibliont.pas para a descrição completa.
   ATENÇÃO     ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    ATENÇÃO    
  SÓ É POSSIVEL VER O CONTEÚDO DO ARQUIVO ATRAVÉS DE UM PROGRAMA QUE IRÁ LER OS REGISTROS
	}
uses BIBLIONT;
VAR ARQS:TEXT;
    ARQD:FILE OF REGIS;
    REGS:STRING[60];
    REGD:REGIS;
    A,B,E,NUM:INTEGER;
Begin
  ASSIGN(ARQS,'CAND.TXT');
  RESET(ARQS);
  ASSIGN(ARQD,'CAND.IND');
  REWRITE(ARQD);
  WHILE NOT EOF(ARQS) DO
   BEGIN
    READLN(ARQS,REGS);//RETIRA DO ARQ E LEVA PARA MP AS INFORMAÇOES DE UM REGISTRO (CAND.TXT)
//MONTA O REGISTRO QUE IRÁ PARA ARQD
    VAL(COPY(REGS,1,4),NUM,E);//RETIRA O NUMERO DO STRING
    REGD.NUM:=NUM;//NUMERO
    REGD.NOME:=COPY(REGS,5,35);//NOME
    REGD.CPF:=COPY(REGS,40,11);//CPF
    REGD.DATA.ANO:=copy(regs,55,4); //ano
    REGD.DATA.MES:=COPY(REGS,53,2); //mes
    REGD.DATA.DIA:=COPY(REGS,51,2); //dia
    VAL(COPY(REGS,59,2),REGD.CAR,E);//CARGO
//POSICIONA
    SEEK(ARQD,A); //<<<<<<COMPARE COM O QUE GERA SAI.DIR (ARQDIR)
//GRAVA NA POSICAO FISICA INDICADA PELO CONTADOR A<<<<<
    WRITE(ARQD,REGD);
		A:=A+1
	 END;
	 WRITELN('GRAVADOS=>',A:5,' REGISTROS--VEJA O TAMANHO DO ARQUIVO -SAI.IND- (ENTER PARA ENCERRAR)');
	 READLN;
	 CLOSE(ARQS);
	 CLOSE(ARQD);  
End.