{11.	FUP que leia uma série de nomes com no máximo 50 caracteres, encerrada por
nome = FIM. Para cada nome lido, mostrar “sobrenome, nome”. Por exemplo: 
leu MARIA DA SILVA XAVIER, mostrar, XAVIER, MARIA DA SILVA. Considerar que 
cada nome lido, possui pelo menos um sobrenome. 
FEITO POR PROFE LUIZ.


=============== ATENÇÃO ATENÇÃO ATENÇÃO-----ENTENDER ===============
===>TODO(A) STRING (CONJUNTO DE CARACTERES) PODE SER TRATADO COMO UM VETOR<=====
ENTÃO
VOU TER QUE ESTUDAR OS MÓDULOS ABAIXO DA BIBLIOTECA DO PASCAL
COPY		RETIRA DE UM STRING UM PEDAÇO DELE
LENGTH  DEVOLVE O TOTAL DE CARACTERES DE UM STRING
VAL 		TRANSFORMA UM STRING EM UM INTEIRO/REAL
STR     TRANSFORMA INTEIRO/REAL EM UM STRING
CHR   	PEGA O CARACTER ASCII INDICADO PELO INTEIRO
UPCASE  TRANSFORMA EM MAIÚSCULA
INSERT  INSERE EM UM STRING OUTRO STRING
DENTRE OUTRAS A PARTIR DE HOJE SÓ LE INFORMAÇÕES DO TECLADO COMO STRING, DEPOIS CONVERTE.
  			 1         2         3         4         5
12345678901234567890123456789012345678901234567890
MARIA DA SILVA XAVIER
							#     @  <<  #=POSICAO DO PRIMEIRO ESPAÇO ANTES DO SOBRENOME (15)
											     #+1= ISN
											     #-1= FN
											     @=FINAL DO SOBRENOME FSN=LENGTH(STRING)
											     
}
Program L2EX11 ;
USES bibliont;
VAR NUM,E:INTEGER ;//OUTRO EXEMPLO
    NUMA:STRING[3];//OUTRO EXEMPLO
//EXERCICIO 11
    NOME:STRING[50];
    ESP,I_SN,F_N,F_SN,A:INTEGER;
Begin
//OUTRO EXEMPLO
 repeat
  WRITE ('NUM=>');
  READLN(NUMA);
  VAL(NUMA,NUM,E); //tenta converter conteudo de numa em um inteiro
  IF(E=0)THEN
   WRITELN(NUMA:6,NUM:6)
  ELSE
   WRITEln('ILEGAL',NUMA:6,num:6,E:6); 
 until(e=0);
 leia1('NUMERO',num);
    WRITELN(NUMA:6,NUM:6);

//FIM OUTRO EXEMPLO
//INICIO DO EXERCÍCIO 11
  WRITE('DIGITE O NOME=>');
  READLN(NOME);
  NOME:=UPCASE(NOME) ;
  WHILE NOME<>'FIM' DO
   BEGIN
    F_SN:=LENGTH(NOME);
    ESP:=F_SN;
    REPEAT
     ESP:=ESP-1;
    UNTIL(NOME[ESP]=' ');
//
    I_SN:=ESP+1;
    f_N:=ESP -1;
    FOR A:=I_SN TO F_SN DO
     WRITE(NOME[A]);
    WRITE(', ');
    FOR A:=1 TO F_N DO
     WRITE(NOME[A]);
    WRITELN;
    WRITE('DIGITE O NOME=>');
    READLN(NOME);
    NOME:=UPCASE(NOME) ;
   END;  
 TERMINE; 
End.